name: basic
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  qr_flutter: ^2.1.0+55
  audioplayers: ^0.13.2
  qrscan: ^0.2.17
  permission: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/moon.png
    - asset/pattern.jpg
    - asset/memphis-mini.png
    - asset/sunset.jpg
    - asset/facebook.png
    - asset/tweeter.png
    - asset/jennie.jpg
  
  fonts:
    - family: BigShouldersDisplay
      fonts:
        - asset: fonts/BigShouldersDisplay-Regular.ttf
        - asset: fonts/BigShouldersDisplay-Thin.ttf
          style: italic
        - asset: fonts/BigShouldersDisplay-Bold.ttf
          weight: 700
